travis:
  secure:
    BINSTAR_TOKEN: enO9g5tpsB9niIQRnHVYUS/n2JdxSO4NmTWi2O1X996JUAn+tpX9ldnd2ioRl0Bg3Zjty6JyqMbA8x93S2QYTlalFFEIyAi56rnskUPgfaIPtDJhQClIdegONdsmOqXNpzmLvxlGvHnoztrSsM4I7uCU1lQLtmXmzYbqnE6782LjuzSan6XxU70DZ0FzLCwHHMolfvwZXWtYLkdFcdkxVOhzAfpgo74UVcMQVmQxVE3Nft66DHnOIk9fiLVkN51ABD8478UvFkV4tlWIhfUVvqaC6e/XHRNaE+TwLWnxhx5fc+GbTxDEnJwxj9G5LERK3hL/C6O1ODTL4yJb3HpGLf4SwJp/N8VFKbmadpKA6vhFNpQwg4nZ7Z12y+t7yWarfaP5xei8jpaDZeEoND4PBIT0dycY24uJ/sYhGfjgidMyLgr+omeAyrR0iasInm3IrAC6wj5smadq93a/FvvKbL6PsKRMllHwdOpDvj/2B8t6/HTgNUlmmxfITma0y+SWCtwloSTmNM5aDzImcotNhjwS6intmYyaL3ha8VHpF5iZ7iPOFPqCps7Dpb70dxdkFDnATP7UzYTD58+wY2FLaYG+bJ1ja9ydn6etgKkU37P7dIr/58cj4iqo7aiwEuPhjOh4X7HEsRLWlV72X6Z75u2JywHnt1CxQEIhwJW6utY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
