travis:
  secure:
    BINSTAR_TOKEN: GRLtMQ7jKdJo2aOhOwcSK7YIVPMWvxW+oU5xzDCqe/5+NcYkS4KHW16jLmLmy6IQQK/0v+V/n1diEMFIBl0W8yWg9VhTJjNs36oDNogH3JpIXr9/0ZJxbciKwcRaeTsYhJQBEva3ZJ/ySg1l2O/DML4SvbPf1qEF2ATrE5eQ8wY3aG/v/LzrWb1L8IKfYY8nFQBMOdV/Z662VVw6L7atJs8smq1hiLmfGBoErf3d2E/HfED7Nx7/aY1Akdqn1T9aXim+4OhFYfPqiyGiHhxWw8j48QL/qSaKgpZ/7+dtY1toGFYFV4LrXU7OkmkVPMbXSq7oISj2nJI/OEH5yB2SGR9Bo6pZR6dwRNTj1+7zhzWMxCvi15g7q50yohnxk3PsWPP/UA3Ri1kaTTphwQ1PuXeCWkJSbyxYOb0MPZSCcPJotNz1iS/dbnVh+Dy3Swq8AOBSYrY3SDE4doV4PL4jjGRxmAXjojq1KFUIlvqPBh6NW+z7GLDk+RE6rmU8o2tiUBa07kd73xFR63HNGmWVfzw8O//J8TJTqkOGoPaBeaPohZ2ES/kY+GEma4qCkmK7XY6D/RT+nXojS571MPi0FzD2ojoUfFZvr4x7GXfyWDZkarFTvn1nDH4DOg3DHN8z1oHCOGola0/Y6seo8inh4wRxRBOCUkwGvyJZoU7owqI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
