travis:
  secure:
    BINSTAR_TOKEN: IyBaY35oK2/ErYFljzKWhrXbUPluidwEEBTCFwKlf6FFSzvQmkV8e+NNSjuZas0IHvTcT7Www306fl9Q6NCl29XcACsLYflIVi1oTSKbIz0+pWcaUIrMZjW9Ocbbzg92p3d+4iUmcKpFp4Vv/82nA0R0qBFhziGrTZZ8QdazAOvZ0j6xcDaSIaEalHyt+zFJx7nZgvflz9Nw4doazGYCvDF2F91BMyZPMwKEYrlaNs15O5zI+HQjPyKTexcDmPnaEA81wI5yYME0reuULY81vQmQqOx7hX9ZK9weD1T2EJmSk/4D5JR2BnFUTpBy77A5m8ZsKWR4PrY+ImtPsKuWafDK+RxS21EMqtNNYptAB2TOTJXMq9nKSxsuABOfCYCpIkfu0n0iKV803MicG0Pn6c1/oCQD9KQeC0IwQKvEmQWhEwYwRSU/XPUZKtT8vIOkQMP1ojGs1RqhuGUUOwl95TclnXWA9RkQpyAwa1xBYzfP6Kc1dFDrfXTDe/SHsEL5J00arbOiaSB2XQifgXuh6XvFa/GHy4YEpXgu8xU9+yu98/GTVf7HISfaHB/8Ooi78Sc5eSW1RBj6luwfbJQyQzpLkhPTdVyZ+8sq083Tfkrwbqce9up4n1QH0ViTcgNFdHEIDQvDYhhGUPzzFQUwuiMIlLyJnhYRK8xQevfVrSA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
